version: '3.2'

services:
  it_tests:
    build:
      context: .
      dockerfile: ./Dockerfile.integration
    volumes:
      - $PWD:/go/src/target
    depends_on:
      - db
    networks:
      - integration-test-example